#include<bits/stdc++.h>
using namespace std;
int main ()
{
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    long long int t,i,a,b;
    cin>>t;
    for(i=1;i<=t;i++)
    {
        cin>>a>>b;
        if(a==b)
        {
            cout<<0<<"\n";
        }
        else
        {
            if(a>b)
            {
                if((a-b)%2==0)
                {
                    cout<<1<<"\n";
                }
                else
                {
                    cout<<2<<"\n";
                }
            }
            else
            {
                if((b-a)%2==0)
                {
                    cout<<2<<"\n";
                }
                else
                {
                    cout<<1<<"\n";
                }
            }
        }
    }
}